import { redirect } from "next/navigation";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { getUserProfile } from "@/actions/auth";
import { UserProvider } from "@/providers/UserProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const profile = await getUserProfile();

  if (!profile) {
    redirect("/login");
  }

  if (!profile?.username) {
    redirect("/login/username");
  }
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <UserProvider userId={profile?.user_id} username={profile?.username}>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
